const app={};

const monsterManual = {
    // name: {
    //     name: "",
    //     Pname: "",
    //     size: "",
    //     type:"",
    //     searchTypes: {
    //          1:"",
    //     },
    //     subtype: "",
    //     searchSubtypes: {
    //          1:"",
    //     },
    //     alignment: "",
    //     armorClass: "",
    //     hitPoints: num,
    //     hitDie: "",
    //     speed: "",
    //     proficiency: num,
    //     str: num,
    //     dex: num,
    //     con: num,
    //     int: num,
    //     wis: num,
    //     cha: num,
    //     savingThrows "",
    //     skills: "",
    //     damageVulerabilites: "",
    //     damageResistance: ""
    //     damageImmunities: "",
    //     conditionImmunities:"",
    //     senses: "",
    //     languges: "",
    //     location: "",
    //     locationTags: {
    //         1: "",
    //     },
    //     triome: "",
    //     triomeTages : {
    //         1: "",
    //     },
    //     cr: num,
    //     traits: "",
    //     mutate: "",
    //     actions:"",
    //     legendaryActions: "",
    //     behaviour: "",
    //     lair: "",
    //     imageUrl: "assets/.png",
    //     imageDiscription: ,
    // },
    adaptiveShimmerer : {
        name: "Adaptive Shimmerer", 
        size: "Large",
        type: "Beast",
        subtype: "",
        alignment: "Unaligned",
        armorClass: "14 (Nautral Armor)",
        hitPoints: 66,
        hitdie: "6d10 + 30",
        speed: "20 ft, climb 20 ft.",
        proficiency: 2,
        str: 18,
        dex: 9,
        con: 20,
        int: 2,
        wis: 16,
        cha: 16,
        savingThrows : "con: +7, cha: 5",
        skills: "",
        damageVulerabilites: "",
        damageResistance: "",
        damageImmunities: "",
        conditionImmunities:"",
        senses: "passive Perception 13",
        languges: "-",
        location: "Forest, Jungle",
        locationTags: {
            1: "Forest",
            2: "Jungle",
        },
        triome: "Indatha, Ketria, Zagoth",
        triomeTages : {
            1: "Indatha",
            2: "Ketria",
            3: "Zagoth"
        },
        cr: 2,
        xp: "(450 xp)",
        traits: "Shimmer. Any area within 60 feet of Adaptive Shimmerer counts as bright light. All creatures within 30 feet of Adaptive Shimmer (including itself) gain disadvantage on sleath checks. ",
        mutate: "Whenever this creature mutates, it gains +2 str and +2 con.",
        actions:"Bite. +5 to hit, reach 5ft, one traget. Hit: 16 (3d8 + 4 piercing damage).",
        legendaryActions: "",
        behaviour: "The Adaptive Shimmerer is usually the larval form of the Luminous Broodmoth, however due to Ikoria's unusual ecology it can mutate into almost any other Ikorian creature. Though quite large compared to humanoids it is quite shy, usually living in trees and eating absurd amounts of leaves.  ",
        lair: "",
        imageUrl: "assets/adaptiveShimmerer.jpg",
        imageDiscription: "Giant Shiny Caturpiller",
    },

    AgitatorAnt   : {
        name: " Agitator Ant",
        type: "Beast",
        subtype: "",
        size: "Small",
        alignment: "Unaligned",
        armorClass: "12 (natural armor)",
        hitPoints: 36,
        hitDie: "(4d6+4)",
        speed: "40ft, climb 30ft.",
        proficiency: 2,
        str: 13,
        dex: 14,
        con: 12,
        int: 2,
        wis: 14,
        cha: 16,
        savingThrows: "cha: +5",
        skills: "Intimidate: +5",
        damageVulerabilites: "",
        damageResistance: "",
        damageImmunities: "",
        conditionImmunities:"Charmed, Frightened",
        senses: "darkvision 60 ft., tremorsesense 60ft., passive Perception 12",
        languges: "-",
        location: "Mountain, Underground",
        locationTags: {
            1: "Mountain",
            2: "Underground",
        },
        triome: "Ketria, Raugrin, Savai",
        triomeTages : {
            1: "Raugrin",
            2: "Ketria",
            3: "Savai"
        },
        cr: 1,
        xp: "(200 xp)",
        traits: "Aggressive. As a bonus action, this creature can move up to its speed toward a hostile creature it can see.",
        mutate: "-",
        actions:"Bite. +3 to hit, reach 5ft, one traget. Hit: 9(2d8 + 1)  piercing damage. On hit target must make a DC 13 Cha saving throw. On failure, target must make a melee attack action on the their next turn, must use it before their movement if a target is in range and must attack a target other that this creature if at least two targets are avalible.",
        legendaryActions: "",
        behaviour: "Agitator Ants are, as the name implies are highly aggressive. Attacking anything that either crosses their path or enters their territory. Living in large colonies on mountains or in underground caves, they will leave their homes in groups of 3-5 to scavegen, hunt for food or run crude patrols of their territory.",
        lair: "",
        imageUrl: "assets/agitatorAnt.jpg",
        imageDiscription: "An arngry red ant",
    },

    // AlmightyBrushwagg   : {
    //     name: "Almighty Brushwagg",
    // //     Pname: "",
    // //     size: "",
    // //      type:"",
    // //     alignment: "",
    // //     armorClass: "",
    // //     hitPoints: num,
    // //     hitDie: "",
    // //     speed: "",
    // //     str: num,
    // //     dex: num,
    // //     con: num,
    // //     int: num,
    // //     wis: num,
    // //     cha: num,
    // //     savingThrows "",
    // //     skills: "",
    // //     damageVulerabilites: "",
    // //     damageResistance: ""
    // //     damageImmunities: "",
    // //     conditionImmunities:"",
    // //     senses: "",
    // //     languges: "",
    // //     location: "",
    // //     locationTags: {
    // //         1: "",
    // //     },
    // //     triome: "",
    // //     triomeTages : {
    // //         1: "",
    // //     },
    // //     cr: num,
    // //     traits: "",
    // //     mutate: "",
    // //     actions:"",
    // //     legendaryActions: "",
    // //     behaviour: "",
    // //     lair: "",
    // //     imageUrl: "assets/.png",
    // //     imageDiscription: ,
    // },

    Archipelagore   : {
        name: "Archipelagore",
        size: "Gargantuan",
        type:"Monstrosity",
        subtype: "titan",
        alignment: "lawful evil",
        armorClass: "19",
        hitPoints: 315,
        hitDie: "(15d20+150)",
        speed: "20 ft., swim 50ft.",
        proficiency: 6,
        str: 26,
        dex: 9,
        con: 30,
        int: 18,
        wis: 22,
        cha: 16,
        savingThrows: "Str: +14, Con: +16, Int: +10, Wis: +12",
        skills: "Stealth: +16, Preception: +12",
        damageVulerabilites: "lightning",
        damageResistance: "cold, fire, bludgeoning from non-magic weapons",
        damageImmunities: "",
        conditionImmunities:"prone while in water",
        senses: "passive preception: 22",
        languges: "understands Primordial and Aquan but can't speak it",
        location: "Coastal, Underwater",
        locationTags: {
            1: "Coastal",
            2: "Underwater"
        },
        triome: "Raugrin",
        triomeTags : {
            1: "Raugrin",
        },
        cr: 17,
        xp: "(18,000 xp)",
        traits: "Ampibious. This creature can breathe air and water. <br> Ambush Predator. If not in combat this creature is always treated as having just made a sleath roll. <br> Siege Monster. This creature deals double damage to objects and structures.",
        mutate: "When this creature mutates, if it is in water, it summons a tidal wave for each time it has mutated this combat. Each wave is a 60 ft long and 20 ft wide and tall. All creatures in the afected area must make a DC 18 Dex saving throw, taking 4d12 damage and being knocked prone on a failure, half damage onn a save.",
        actions:"Multiattack: This creature makes three attacks, one bite attack and two claw attacks. <br> Bite: Melee Weapon Attack: +14 to hit, reach 10 ft., one target. Hit: 21 (3d8 + 8) piercing damage. If the target is a Large or smaller creature, it must succeed on a DC 18 Dexterity saving throw or be swallowed by this creature. A swallowed creature is Blinded and Restrained, it has total cover against attacks and other Effects outside the worm, and it takes 21 (6d6) acid damage at the start of each of the worm's turns. If this creature takes 30 damage or more on a single turn from a creature inside it, this creature must succeed on a DC 21 Constitution saving throw at the end of that turn or regurgitate all swallowed creatures, which fall prone in a space within 10 feet of this creature. If this creature dies, a swallowed creature is no longer Restrained by it and can escape from the corpse by using 20 feet of Movement, exiting prone. <br> Claw: +14 to hit, reach 15 ft., one target. Hit: 32 (3d12 + 8) slashing damage. If the target is large or smaller it must make a DC 19 Str saving throw, on a failure they are grappled.",
        legendaryActions: "Legendary Actions: This creature can take 3 legendary actions, choosing from the options below. Only one legendary action option can be used at a time and only at the end of another creature’s turn. This creature regains spent legendary actions at the start of their turn. <br>Detect.This creature makes a Wisdom (Perception) check. <br> Bite. This creature preforms a bite attack against a creature it has currently grappled. <br> Summon Aquatic Creatures. This creature summons a group of one or morecreatures. These creatures must all have a swim speed and their total Challenege Rating combined must not excide 2.",
        behaviour: "The Archipelagore is an ambush hunter, the largest one on all of Ikoria. It swims around at a slow pace allowing saliors and fish to approach it, then proceieds to grab them with its massive claws and force them into it's mouth to eat them. If creatures try to comunicate with the Archipelagore it will say it's safe then try to eat them. If the creatures try to make a deal for access to the Archipelagore's island back it may grant it, particulaly if they offer acess to more food. <br> The Archipelagore's back is a small island, it can act as a mobile sancuary for up to 25 medium or smaller creatures.",
        lair: "",
        imageUrl: "assets/archipelagore.jpg",
        imageDiscription: "A kraken with the back of a mounatin",
    },  
    
    AuspiciousStarrix  : {
        name: "Auspicious Starrix",
        size: "Huge",
        type:"Fey",
        subtype: "",
        alignment: "Chaotic Neutral",
        armorClass: "19 (Nautral Armour)",
        hitPoints: 179,
        hitDie: "(17d12+68)",
        speed: "60 ft.",
        proficiency: 3,
        str: 19,
        dex: 16,
        con: 20,
        int: 10,
        wis: 14,
        cha: 18,
        savingThrows: "CHA: +7",
        skills: "Intimidation: +7, Perception: +5, Insight: +5",
        damageVulerabilites: "",
        damageResistance: "",
        damageImmunities: "",
        conditionImmunities: "Charmed",
        senses: "Passive Perception",
        languges: "Common, Sylvan",
        location: "Forest, Jungle",
        locationTags: {
            1: "Forest",
            2: "Jungle",
        },
        triome: "Indartha, Ketria, Zagoth",
        triomeTages : {
            1: "Indartha",
            2: "Ketria",
            3: "Zagoth"
        },
        cr: 7,
        xp: "(2,900)",
        traits: "Charge. If this creature moves at least 20 ft. straight toward a target and then hits it with a ram attack on the same turn, the target takes an extra 13 (4d6) damage. If the target is a creature, it must succeed on a DC 14 Strength saving throw or be knocked prone. <br> Auspicious Fortune (3/day). This creature can choose to replace the result of any d20 roll with a 15. <br>Magic Resitance. This creature has advantage on saving throws against spells and other magical effects.",
        mutate: "When this creature mutates it casts Conjure Woodland Beings (at 4th level) for each time it has mutates this combat.",
        actions:"Multiattack. This creature makes 3 attacks: one with its ram and two with its hooves. Ram. Melee Weapon Attack: +7 to hit, reach 5 ft., one target. Hit: 11(2d6 + 4) bludgeoning damage. <br> Hooves. Melee Weapon Attack: +7 to hit, reach 5 ft., one prone creature. Hit: 20(4d8 + 4) bludgeoning damage",
        legendaryActions: "",
        behaviour: "A proud creature which waltzs around the forests of Ikoria. It moves with the confidence of a creature whos sucess is asured and is dotted on my a court, because it somewhat does. It has some minior conjuration and divination powers, allow it to summon allies and see beneficial futures.",
        lair: "",
        imageUrl: "assets/auspiciousStarrix.jpg",
        imageDiscription: "A green, fey, elk-like creature.",
},

    AvianOddity  : {
        name: "Avian Oddity",
        size: "Large",
        type:"Beast",
        subtype: "",
        alignment: "Neutral",
        armorClass: "14",
        hitPoints: 44,
        hitDie: "(6d10+12)",
        speed: "10 ft., Flight 60 ft.",
        str: 16,
        dex: 18,
        con: 14,
        int: 8,
        wis: 14,
        cha: 6,
        savingThrows: "",
        skills: "Perception +4, Intimidation: +4",
        damageVulerabilites: "",
        damageResistance: "",
        damageImmunities: "",
        senses: "passive Precption 14",
        languges: "Understands Common And Auran But Can't Speak",
        location: "Coastal, Grassland, Hill, Forest, Mountain",
        locationTags: {
            1: "Coastal",
            2: "Grassland",
            3: "Hill",
            4: "Forest",
            5: "Mountain"
        },
        triome: "Ketria, Raugrin, Zagoth",
        triomeTages : {
            1: "Raugrin",
            2: "Ketria",
            3: "Zagoth"
        },
        cr: 1,
        xp: "(200 xp)",
        traits: "Keen Sight. This creature has advantage on Wisdom (Perception) checks that rely on sight. <br> Gift of Feathers (1/day). Once per day this Creature can give one willing creature within 30 feet of it a flying speed of 60 feet. This effect last untill that creature's next long rest",
        mutate: "",
        actions:"Multiattack. This creature makes two attacks: one with its beak and one with its talons. <br>Beak. Melee Weapon Attack: +5 to hit, reach 5 ft., one target. Hit: 6 (1d6 + 3) piercing damage. <br>Talons. Melee Weapon Attack: +5 to hit, reach 5 ft., one target. Hit: 10 (2d6 + 3) slashing damage.",
        legendaryActions: "",
        behaviour: "A odd creature to say the least. Lower on the food than most of Ikoria's monsters it eats bugs, fruit and tiny vermin. It avoids larger predators with flight or puffing itself up and strenching out it's many, mnay wings. It sometimes gains allies by gift flight onto tougher creatures in exchange for protection.",
        lair: "",
        imageUrl: "assets/AvianOddity.jpg",
        imageDiscription: "A bizzare bird-like crature with dozens of wings.",
    },

    BlisterspitGremlin  : {
        name: "Blisterspit Gremlin",
        size: "small",
        type:"Monstrosities",
        subtype: "",
        alignment: "Chaotic Evil",
        armorClass: "13 (nautral armor)",
        hitPoints: 26,
        hitDie: "6d6+6",
        speed: "30ft. Climb 20ft.",
        str: 12,
        dex: 14,
        con: 13,
        int: 9,
        wis: 8,
        cha: 6,
        savingThrows: "",
        skills: "Sleight of Hand +4, Stealth +4",
        damageVulerabilites: "",
        damageResistance: "",
        damageImmunities: "",
        senses: "passive Perception 9",
        languges: "Crude Common and Goblin",
        location: "Mountain",
        locationTags: {
            1: "Mountain"
        },
        triome: "Ketria, Raugrin, Savai",
        triomeTages : {
            1: "Raugrin",
            2: "Ketria",
            3: "Savai"
        },
        cr: 0.5,
        traits: "Magic Resitance. This creature has advantage on saving throws against spells and other magical effects. <br>Reaction. If a spell was cast within 60 feet of the this creature it can use its Blister Spit as a reaction.",
        mutate: "",
        actions:"Claw. Melee Weapon Attack: +4 to hit, reach 5 ft., one target. This creature deals 11 (2d8+2) slashing damage. <br>Blister Spit. Ranged weapon attack: +5 to hit, range 30 ft., one target This creature deals 9 (2d6+2) fire damage.",
        legendaryActions: "",
        behaviour: "A spiteful and hateful creature. It spents most of it's time stealing then hording small, magical objects in cliff side nest. It will attack adventuring parties with magic items in an attemp to steal them. It usually ambushes prey by hiding in canyon walls or caves and then surprising foes at the bottom by poping out and using it's spit attack against them.",
        lair: "",
        imageUrl: "assets/blisterSpit.jpg",
        imageDiscription: "an angry gremlin hang off a cliff, spliting a fireball",
    },

    BlitzLeech  : {
    //     name: "",
    //     Pname: "",
    //     size: "",
    //     alignment: "",
    //     armorClass: "",
    //     hitPoints: num,
    //     hitDie: "",
    //     speed: "",
    //     str: num,
    //     dex: num,
    //     con: num,
    //     int: num,
    //     wis: num,
    //     cha: num,
    //     savingThrows "",
    //     skills: "",
    //     damageVulerabilites: "",
    //     damageResistance
    //     damageImmunities: "",
    //     senses: "",
    //     languges: "",
    //     cr: num,
    //     traits: "",
    //     mutate: "",
    //     actions:"",
    //     legendaryActions: "",
    //     behaviour: "",
    //     lair: "",
    //     imageUrl: "assets/.png",
    //     imageDiscription: ,
},

    BoneyardLurker   : {
        //     name: "",
        //     Pname: "",
        //     size: "",
        //     alignment: "",
        //     armorClass: "",
        //     hitPoints: num,
        //     hitDie: "",
        //     speed: "",
        //     str: num,
        //     dex: num,
        //     con: num,
        //     int: num,
        //     wis: num,
        //     cha: num,
        //     savingThrows "",
        //     skills: "",
        //     damageVulerabilites: "",
        //     damageResistance
        //     damageImmunities: "",
        //     senses: "",
        //     languges: "",
        //     cr: num,
        //     traits: "",
        //     mutate: "",
        //     actions:"",
        //     legendaryActions: "",
        //     behaviour: "",
        //     lair: "",
        //     imageUrl: "assets/.png",
        //     imageDiscription: ,
    },

    BoneyardMycodrax   : {
        //     name: "",
        //     Pname: "",
        //     size: "",
        //     alignment: "",
        //     armorClass: "",
        //     hitPoints: num,
        //     hitDie: "",
        //     speed: "",
        //     str: num,
        //     dex: num,
        //     con: num,
        //     int: num,
        //     wis: num,
        //     cha: num,
        //     savingThrows "",
        //     skills: "",
        //     damageVulerabilites: "",
        //     damageResistance
        //     damageImmunities: "",
        //     senses: "",
        //     languges: "",
        //     cr: num,
        //     traits: "",
        //     mutate: "",
        //     actions:"",
        //     legendaryActions: "",
        //     behaviour: "",
        //     lair: "",
        //     imageUrl: "assets/.png",
        //     imageDiscription: ,
    },

    BootNipper   : {
        name: "Boot Nipper",
        size: "Tiny",
        type:"Monstrosities",
        subtype: "",
        alignment: "Chaotic Evil",
        armorClass: "14",
        hitPoints: 36,
        hitDie: "(8d8+16)",
        speed: "30 ft.",
        str: 14,
        dex: 16,
        con: 15,
        int: 5,
        wis: 13,
        cha: 6,
        savingThrows: "",
        skills: "Stealth +6",
        damageVulerabilites: "",
        damageResistance: "",
        damageImmunities: "",
        senses: "darkvision 60ft., passive Perception 11",
        languges: "",
        location: "Forest, Grassland, Swamp, Underdark, Boneyard",
        locationTags: {
            1: "Forest",
            2: "Grassland",
            3: "Swamp",
            4: "Underdark",
            5: "Boneyard"
        },
        triome: "Indatha, Savai, Zagoth",
        triomeTages : {
            1: "Indatha",
            2: "Zagoth",
            3: "Savai"
        },
        cr: 2,
        traits: "Branching Mutations. This creature has one of the two following abilities: Life Drain or Necrotic Bite. <Br>Life Drain. When this creature makes a sucessful melee weapon attack it regains hit points equal to half the damage it dealth rounded up. <br>Necrotic Bite. This creatures melee wepons attack deal an extra 5 (2d8) necrotic damage.",
        mutate: "",
        actions:"Bite. Melee Weapon Attack: +4 to hit, reach 5ft. Hit: Deals 16 (3d6+6) piercing damage. If the target is large sized or larger the target must make a DC 13 Dex save. On a failure they fall prone, on sucess they lose half their movement next round.",
        legendaryActions: "",
        behaviour: "A Sleathy hunter, this tiny but aggressive creature stalks larger prey in enviroments where plant growth and underbush help concel itself. It has learned the way to attack larger prey is to bite at the feet, toes and ankles, causing it to fall over. It then either goes for the throat to kill or takes a few bites and runs away. It loves the taste of toes in particular and can bite through leather and sometimes even metal to get to them. It favours bipedal humaniods, as their two legs mean they are more easily prove to losing balance. Through small, it is pound for pound one of the deadlest and most aggressive monster on Ikoria.",
        lair: "",
        imageUrl: "assets/bootNipper.jpg",
        imageDiscription: "A horrorifing little monster with a beak mouth and a touge coming out of the mouth with another mouth in it.",
},

Capricopian   : {
    //     name: "",
    //     Pname: "",
    //     size: "",
    //     alignment: "",
    //     armorClass: "",
    //     hitPoints: num,
    //     hitDie: "",
    //     speed: "",
    //     str: num,
    //     dex: num,
    //     con: num,
    //     int: num,
    //     wis: num,
    //     cha: num,
    //     savingThrows "",
    //     skills: "",
    //     damageVulerabilites: "",
    //     damageResistance
    //     damageImmunities: "",
    //     senses: "",
    //     languges: "",
    //     cr: num,
    //     traits: "",
    //     mutate: "",
    //     actions:"",
    //     legendaryActions: "",
    //     behaviour: "",
    //     lair: "",
    //     imageUrl: "assets/.png",
    //     imageDiscription: ,
},

CavernWhisperer   : {
    //     name: "",
    //     Pname: "",
    //     size: "",
    //     alignment: "",
    //     armorClass: "",
    //     hitPoints: num,
    //     hitDie: "",
    //     speed: "",
    //     str: num,
    //     dex: num,
    //     con: num,
    //     int: num,
    //     wis: num,
    //     cha: num,
    //     savingThrows "",
    //     skills: "",
    //     damageVulerabilites: "",
    //     damageResistance
    //     damageImmunities: "",
    //     senses: "",
    //     languges: "",
    //     cr: num,
    //     traits: "",
    //     mutate: "",
    //     actions:"",
    //     legendaryActions: "",
    //     behaviour: "",
    //     lair: "",
    //     imageUrl: "assets/.png",
    //     imageDiscription: ,
},

ChitteringHarvester   : {
    //     name: "",
    //     Pname: "",
    //     size: "",
    //     alignment: "",
    //     armorClass: "",
    //     hitPoints: num,
    //     hitDie: "",
    //     speed: "",
    //     str: num,
    //     dex: num,
    //     con: num,
    //     int: num,
    //     wis: num,
    //     cha: num,
    //     savingThrows "",
    //     skills: "",
    //     damageVulerabilites: "",
    //     damageResistance
    //     damageImmunities: "",
    //     senses: "",
    //     languges: "",
    //     cr: num,
    //     traits: "",
    //     mutate: "",
    //     actions:"",
    //     legendaryActions: "",
    //     behaviour: "",
    //     lair: "",
    //     imageUrl: "assets/.png",
    //     imageDiscription: ,
},

Cloudpiercer  : {
    //     name: "",
    //     Pname: "",
    //     size: "",
    //     alignment: "",
    //     armorClass: "",
    //     hitPoints: num,
    //     hitDie: "",
    //     speed: "",
    //     str: num,
    //     dex: num,
    //     con: num,
    //     int: num,
    //     wis: num,
    //     cha: num,
    //     savingThrows "",
    //     skills: "",
    //     damageVulerabilites: "",
    //     damageResistance
    //     damageImmunities: "",
    //     senses: "",
    //     languges: "",
    //     cr: num,
    //     traits: "",
    //     mutate: "",
    //     actions:"",
    //     legendaryActions: "",
    //     behaviour: "",
    //     lair: "",
    //     imageUrl: "assets/.png",
    //     imageDiscription: ,
},

CrypticTrilobite  : {
    //     name: "",
    //     Pname: "",
    //     size: "",
    //     alignment: "",
    //     armorClass: "",
    //     hitPoints: num,
    //     hitDie: "",
    //     speed: "",
    //     str: num,
    //     dex: num,
    //     con: num,
    //     int: num,
    //     wis: num,
    //     cha: num,
    //     savingThrows "",
    //     skills: "",
    //     damageVulerabilites: "",
    //     damageResistance
    //     damageImmunities: "",
    //     senses: "",
    //     languges: "",
    //     cr: num,
    //     traits: "",
    //     mutate: "",
    //     actions:"",
    //     legendaryActions: "",
    //     behaviour: "",
    //     lair: "",
    //     imageUrl: "assets/.png",
    //     imageDiscription: ,
},

CrystallineGiant  : {
    //     name: "",
    //     Pname: "",
    //     size: "",
    //     alignment: "",
    //     armorClass: "",
    //     hitPoints: num,
    //     hitDie: "",
    //     speed: "",
    //     str: num,
    //     dex: num,
    //     con: num,
    //     int: num,
    //     wis: num,
    //     cha: num,
    //     savingThrows "",
    //     skills: "",
    //     damageVulerabilites: "",
    //     damageResistance
    //     damageImmunities: "",
    //     senses: "",
    //     languges: "",
    //     cr: num,
    //     traits: "",
    //     mutate: "",
    //     actions:"",
    //     legendaryActions: "",
    //     behaviour: "",
    //     lair: "",
    //     imageUrl: "assets/.png",
    //     imageDiscription: ,
},

Cubwarden  : {
    //     name: "",
    //     Pname: "",
    //     size: "",
    //     alignment: "",
    //     armorClass: "",
    //     hitPoints: num,
    //     hitDie: "",
    //     speed: "",
    //     str: num,
    //     dex: num,
    //     con: num,
    //     int: num,
    //     wis: num,
    //     cha: num,
    //     savingThrows "",
    //     skills: "",
    //     damageVulerabilites: "",
    //     damageResistance
    //     damageImmunities: "",
    //     senses: "",
    //     languges: "",
    //     cr: num,
    //     traits: "",
    //     mutate: "",
    //     actions:"",
    //     legendaryActions: "",
    //     behaviour: "",
    //     lair: "",
    //     imageUrl: "assets/.png",
    //     imageDiscription: ,
},

DirgeBat  : {
    //     name: "",
    //     Pname: "",
    //     size: "",
    //     alignment: "",
    //     armorClass: "",
    //     hitPoints: num,
    //     hitDie: "",
    //     speed: "",
    //     str: num,
    //     dex: num,
    //     con: num,
    //     int: num,
    //     wis: num,
    //     cha: num,
    //     savingThrows "",
    //     skills: "",
    //     damageVulerabilites: "",
    //     damageResistance
    //     damageImmunities: "",
    //     senses: "",
    //     languges: "",
    //     cr: num,
    //     traits: "",
    //     mutate: "",
    //     actions:"",
    //     legendaryActions: "",
    //     behaviour: "",
    //     lair: "",
    //     imageUrl: "assets/.png",
    //     imageDiscription: ,
},

DreamtailHeron  : {
    //     name: "",
    //     Pname: "",
    //     size: "",
    //     alignment: "",
    //     armorClass: "",
    //     hitPoints: num,
    //     hitDie: "",
    //     speed: "",
    //     str: num,
    //     dex: num,
    //     con: num,
    //     int: num,
    //     wis: num,
    //     cha: num,
    //     savingThrows "",
    //     skills: "",
    //     damageVulerabilites: "",
    //     damageResistance
    //     damageImmunities: "",
    //     senses: "",
    //     languges: "",
    //     cr: num,
    //     traits: "",
    //     mutate: "",
    //     actions:"",
    //     legendaryActions: "",
    //     behaviour: "",
    //     lair: "",
    //     imageUrl: "assets/.png",
    //     imageDiscription: ,
},

EssenceSymbiote  : {
    //     name: "",
    //     Pname: "",
    //     size: "",
    //     alignment: "",
    //     armorClass: "",
    //     hitPoints: num,
    //     hitDie: "",
    //     speed: "",
    //     str: num,
    //     dex: num,
    //     con: num,
    //     int: num,
    //     wis: num,
    //     cha: num,
    //     savingThrows "",
    //     skills: "",
    //     damageVulerabilites: "",
    //     damageResistance
    //     damageImmunities: "",
    //     senses: "",
    //     languges: "",
    //     cr: num,
    //     traits: "",
    //     mutate: "",
    //     actions:"",
    //     legendaryActions: "",
    //     behaviour: "",
    //     lair: "",
    //     imageUrl: "assets/.png",
    //     imageDiscription: ,
},

EtherealForager  : {
    //     name: "",
    //     Pname: "",
    //     size: "",
    //     alignment: "",
    //     armorClass: "",
    //     hitPoints: num,
    //     hitDie: "",
    //     speed: "",
    //     str: num,
    //     dex: num,
    //     con: num,
    //     int: num,
    //     wis: num,
    //     cha: num,
    //     savingThrows "",
    //     skills: "",
    //     damageVulerabilites: "",
    //     damageResistance
    //     damageImmunities: "",
    //     senses: "",
    //     languges: "",
    //     cr: num,
    //     traits: "",
    //     mutate: "",
    //     actions:"",
    //     legendaryActions: "",
    //     behaviour: "",
    //     lair: "",
    //     imageUrl: "assets/.png",
    //     imageDiscription: ,
},

EverquillPhoenix  : {
    //     name: "",
    //     Pname: "",
    //     size: "",
    //     alignment: "",
    //     armorClass: "",
    //     hitPoints: num,
    //     hitDie: "",
    //     speed: "",
    //     str: num,
    //     dex: num,
    //     con: num,
    //     int: num,
    //     wis: num,
    //     cha: num,
    //     savingThrows "",
    //     skills: "",
    //     damageVulerabilites: "",
    //     damageResistance
    //     damageImmunities: "",
    //     senses: "",
    //     languges: "",
    //     cr: num,
    //     traits: "",
    //     mutate: "",
    //     actions:"",
    //     legendaryActions: "",
    //     behaviour: "",
    //     lair: "",
    //     imageUrl: "assets/.png",
    //     imageDiscription: ,
},

ExcavationMole  : {
    //     name: "",
    //     Pname: "",
    //     size: "",
    //     alignment: "",
    //     armorClass: "",
    //     hitPoints: num,
    //     hitDie: "",
    //     speed: "",
    //     str: num,
    //     dex: num,
    //     con: num,
    //     int: num,
    //     wis: num,
    //     cha: num,
    //     savingThrows "",
    //     skills: "",
    //     damageVulerabilites: "",
    //     damageResistance
    //     damageImmunities: "",
    //     senses: "",
    //     languges: "",
    //     cr: num,
    //     traits: "",
    //     mutate: "",
    //     actions:"",
    //     legendaryActions: "",
    //     behaviour: "",
    //     lair: "",
    //     imageUrl: "assets/.png",
    //     imageDiscription: ,
},

ExuberantWolfbear  : {
    //     name: "",
    //     Pname: "",
    //     size: "",
    //     alignment: "",
    //     armorClass: "",
    //     hitPoints: num,
    //     hitDie: "",
    //     speed: "",
    //     str: num,
    //     dex: num,
    //     con: num,
    //     int: num,
    //     wis: num,
    //     cha: num,
    //     savingThrows "",
    //     skills: "",
    //     damageVulerabilites: "",
    //     damageResistance
    //     damageImmunities: "",
    //     senses: "",
    //     languges: "",
    //     cr: num,
    //     traits: "",
    //     mutate: "",
    //     actions:"",
    //     legendaryActions: "",
    //     behaviour: "",
    //     lair: "",
    //     imageUrl: "assets/.png",
    //     imageDiscription: ,
},

Farfinder  : {
    //     name: "",
    //     Pname: "",
    //     size: "",
    //     alignment: "",
    //     armorClass: "",
    //     hitPoints: num,
    //     hitDie: "",
    //     speed: "",
    //     str: num,
    //     dex: num,
    //     con: num,
    //     int: num,
    //     wis: num,
    //     cha: num,
    //     savingThrows "",
    //     skills: "",
    //     damageVulerabilites: "",
    //     damageResistance
    //     damageImmunities: "",
    //     senses: "",
    //     languges: "",
    //     cr: num,
    //     traits: "",
    //     mutate: "",
    //     actions:"",
    //     legendaryActions: "",
    //     behaviour: "",
    //     lair: "",
    //     imageUrl: "assets/.png",
    //     imageDiscription: ,
},

FerociousTigorilla  : {
    //     name: "",
    //     Pname: "",
    //     size: "",
    //     alignment: "",
    //     armorClass: "",
    //     hitPoints: num,
    //     hitDie: "",
    //     speed: "",
    //     str: num,
    //     dex: num,
    //     con: num,
    //     int: num,
    //     wis: num,
    //     cha: num,
    //     savingThrows "",
    //     skills: "",
    //     damageVulerabilites: "",
    //     damageResistance
    //     damageImmunities: "",
    //     senses: "",
    //     languges: "",
    //     cr: num,
    //     traits: "",
    //     mutate: "",
    //     actions:"",
    //     legendaryActions: "",
    //     behaviour: "",
    //     lair: "",
    //     imageUrl: "assets/.png",
    //     imageDiscription: ,
},

FiendArtisan  : {
    //     name: "",
    //     Pname: "",
    //     size: "",
    //     alignment: "",
    //     armorClass: "",
    //     hitPoints: num,
    //     hitDie: "",
    //     speed: "",
    //     str: num,
    //     dex: num,
    //     con: num,
    //     int: num,
    //     wis: num,
    //     cha: num,
    //     savingThrows "",
    //     skills: "",
    //     damageVulerabilites: "",
    //     damageResistance
    //     damageImmunities: "",
    //     senses: "",
    //     languges: "",
    //     cr: num,
    //     traits: "",
    //     mutate: "",
    //     actions:"",
    //     legendaryActions: "",
    //     behaviour: "",
    //     lair: "",
    //     imageUrl: "assets/.png",
    //     imageDiscription: ,
},

FlourishingFox  : {
    //     name: "",
    //     Pname: "",
    //     size: "",
    //     alignment: "",
    //     armorClass: "",
    //     hitPoints: num,
    //     hitDie: "",
    //     speed: "",
    //     str: num,
    //     dex: num,
    //     con: num,
    //     int: num,
    //     wis: num,
    //     cha: num,
    //     savingThrows "",
    //     skills: "",
    //     damageVulerabilites: "",
    //     damageResistance
    //     damageImmunities: "",
    //     senses: "",
    //     languges: "",
    //     cr: num,
    //     traits: "",
    //     mutate: "",
    //     actions:"",
    //     legendaryActions: "",
    //     behaviour: "",
    //     lair: "",
    //     imageUrl: "assets/.png",
    //     imageDiscription: ,
},

FlycatcherGiraffid  : {
    //     name: "",
    //     Pname: "",
    //     size: "",
    //     alignment: "",
    //     armorClass: "",
    //     hitPoints: num,
    //     hitDie: "",
    //     speed: "",
    //     str: num,
    //     dex: num,
    //     con: num,
    //     int: num,
    //     wis: num,
    //     cha: num,
    //     savingThrows "",
    //     skills: "",
    //     damageVulerabilites: "",
    //     damageResistance
    //     damageImmunities: "",
    //     senses: "",
    //     languges: "",
    //     cr: num,
    //     traits: "",
    //     mutate: "",
    //     actions:"",
    //     legendaryActions: "",
    //     behaviour: "",
    //     lair: "",
    //     imageUrl: "assets/.png",
    //     imageDiscription: ,
},

FrostLynx  : {
    //     name: "",
    //     Pname: "",
    //     size: "",
    //     alignment: "",
    //     armorClass: "",
    //     hitPoints: num,
    //     hitDie: "",
    //     speed: "",
    //     str: num,
    //     dex: num,
    //     con: num,
    //     int: num,
    //     wis: num,
    //     cha: num,
    //     savingThrows "",
    //     skills: "",
    //     damageVulerabilites: "",
    //     damageResistance
    //     damageImmunities: "",
    //     senses: "",
    //     languges: "",
    //     cr: num,
    //     traits: "",
    //     mutate: "",
    //     actions:"",
    //     legendaryActions: "",
    //     behaviour: "",
    //     lair: "",
    //     imageUrl: "assets/.png",
    //     imageDiscription: ,
},

Gemrazer  : {
    //     name: "",
    //     Pname: "",
    //     size: "",
    //     alignment: "",
    //     armorClass: "",
    //     hitPoints: num,
    //     hitDie: "",
    //     speed: "",
    //     str: num,
    //     dex: num,
    //     con: num,
    //     int: num,
    //     wis: num,
    //     cha: num,
    //     savingThrows "",
    //     skills: "",
    //     damageVulerabilites: "",
    //     damageResistance
    //     damageImmunities: "",
    //     senses: "",
    //     languges: "",
    //     cr: num,
    //     traits: "",
    //     mutate: "",
    //     actions:"",
    //     legendaryActions: "",
    //     behaviour: "",
    //     lair: "",
    //     imageUrl: "assets/.png",
    //     imageDiscription: ,
},

Glimmerbell  : {
    //     name: "",
    //     Pname: "",
    //     size: "",
    //     alignment: "",
    //     armorClass: "",
    //     hitPoints: num,
    //     hitDie: "",
    //     speed: "",
    //     str: num,
    //     dex: num,
    //     con: num,
    //     int: num,
    //     wis: num,
    //     cha: num,
    //     savingThrows "",
    //     skills: "",
    //     damageVulerabilites: "",
    //     damageResistance
    //     damageImmunities: "",
    //     senses: "",
    //     languges: "",
    //     cr: num,
    //     traits: "",
    //     mutate: "",
    //     actions:"",
    //     legendaryActions: "",
    //     behaviour: "",
    //     lair: "",
    //     imageUrl: "assets/.png",
    //     imageDiscription: ,
},

GloomPangolin  : {
    //     name: "",
    //     Pname: "",
    //     size: "",
    //     alignment: "",
    //     armorClass: "",
    //     hitPoints: num,
    //     hitDie: "",
    //     speed: "",
    //     str: num,
    //     dex: num,
    //     con: num,
    //     int: num,
    //     wis: num,
    //     cha: num,
    //     savingThrows "",
    //     skills: "",
    //     damageVulerabilites: "",
    //     damageResistance
    //     damageImmunities: "",
    //     senses: "",
    //     languges: "",
    //     cr: num,
    //     traits: "",
    //     mutate: "",
    //     actions:"",
    //     legendaryActions: "",
    //     behaviour: "",
    //     lair: "",
    //     imageUrl: "assets/.png",
    //     imageDiscription: ,
},

GlowstoneRecluse  : {
    //     name: "",
    //     Pname: "",
    //     size: "",
    //     alignment: "",
    //     armorClass: "",
    //     hitPoints: num,
    //     hitDie: "",
    //     speed: "",
    //     str: num,
    //     dex: num,
    //     con: num,
    //     int: num,
    //     wis: num,
    //     cha: num,
    //     savingThrows "",
    //     skills: "",
    //     damageVulerabilites: "",
    //     damageResistance
    //     damageImmunities: "",
    //     senses: "",
    //     languges: "",
    //     cr: num,
    //     traits: "",
    //     mutate: "",
    //     actions:"",
    //     legendaryActions: "",
    //     behaviour: "",
    //     lair: "",
    //     imageUrl: "assets/.png",
    //     imageDiscription: ,
},

Grimdancer  : {
    //     name: "",
    //     Pname: "",
    //     size: "",
    //     alignment: "",
    //     armorClass: "",
    //     hitPoints: num,
    //     hitDie: "",
    //     speed: "",
    //     str: num,
    //     dex: num,
    //     con: num,
    //     int: num,
    //     wis: num,
    //     cha: num,
    //     savingThrows "",
    //     skills: "",
    //     damageVulerabilites: "",
    //     damageResistance
    //     damageImmunities: "",
    //     senses: "",
    //     languges: "",
    //     cr: num,
    //     traits: "",
    //     mutate: "",
    //     actions:"",
    //     legendaryActions: "",
    //     behaviour: "",
    //     lair: "",
    //     imageUrl: "assets/.png",
    //     imageDiscription: ,
},

HelicaGlider  : {
    //     name: "",
    //     Pname: "",
    //     size: "",
    //     alignment: "",
    //     armorClass: "",
    //     hitPoints: num,
    //     hitDie: "",
    //     speed: "",
    //     str: num,
    //     dex: num,
    //     con: num,
    //     int: num,
    //     wis: num,
    //     cha: num,
    //     savingThrows "",
    //     skills: "",
    //     damageVulerabilites: "",
    //     damageResistance
    //     damageImmunities: "",
    //     senses: "",
    //     languges: "",
    //     cr: num,
    //     traits: "",
    //     mutate: "",
    //     actions:"",
    //     legendaryActions: "",
    //     behaviour: "",
    //     lair: "",
    //     imageUrl: "assets/.png",
    //     imageDiscription: ,
},

HeraldOfTheForgotten  : {
    //     name: "",
    //     Pname: "",
    //     size: "",
    //     alignment: "",
    //     armorClass: "",
    //     hitPoints: num,
    //     hitDie: "",
    //     speed: "",
    //     str: num,
    //     dex: num,
    //     con: num,
    //     int: num,
    //     wis: num,
    //     cha: num,
    //     savingThrows "",
    //     skills: "",
    //     damageVulerabilites: "",
    //     damageResistance
    //     damageImmunities: "",
    //     senses: "",
    //     languges: "",
    //     cr: num,
    //     traits: "",
    //     mutate: "",
    //     actions:"",
    //     legendaryActions: "",
    //     behaviour: "",
    //     lair: "",
    //     imageUrl: "assets/.png",
    //     imageDiscription: ,
},

HuntedNightmare  : {
    //     name: "",
    //     Pname: "",
    //     size: "",
    //     alignment: "",
    //     armorClass: "",
    //     hitPoints: num,
    //     hitDie: "",
    //     speed: "",
    //     str: num,
    //     dex: num,
    //     con: num,
    //     int: num,
    //     wis: num,
    //     cha: num,
    //     savingThrows "",
    //     skills: "",
    //     damageVulerabilites: "",
    //     damageResistance
    //     damageImmunities: "",
    //     senses: "",
    //     languges: "",
    //     cr: num,
    //     traits: "",
    //     mutate: "",
    //     actions:"",
    //     legendaryActions: "",
    //     behaviour: "",
    //     lair: "",
    //     imageUrl: "assets/.png",
    //     imageDiscription: ,
},

HuntmasterLiger  : {
    //     name: "",
    //     Pname: "",
    //     size: "",
    //     alignment: "",
    //     armorClass: "",
    //     hitPoints: num,
    //     hitDie: "",
    //     speed: "",
    //     str: num,
    //     dex: num,
    //     con: num,
    //     int: num,
    //     wis: num,
    //     cha: num,
    //     savingThrows "",
    //     skills: "",
    //     damageVulerabilites: "",
    //     damageResistance
    //     damageImmunities: "",
    //     senses: "",
    //     languges: "",
    //     cr: num,
    //     traits: "",
    //     mutate: "",
    //     actions:"",
    //     legendaryActions: "",
    //     behaviour: "",
    //     lair: "",
    //     imageUrl: "assets/.png",
    //     imageDiscription: ,
},

InsatiableHemophage  : {
    //     name: "",
    //     Pname: "",
    //     size: "",
    //     alignment: "",
    //     armorClass: "",
    //     hitPoints: num,
    //     hitDie: "",
    //     speed: "",
    //     str: num,
    //     dex: num,
    //     con: num,
    //     int: num,
    //     wis: num,
    //     cha: num,
    //     savingThrows "",
    //     skills: "",
    //     damageVulerabilites: "",
    //     damageResistance
    //     damageImmunities: "",
    //     senses: "",
    //     languges: "",
    //     cr: num,
    //     traits: "",
    //     mutate: "",
    //     actions:"",
    //     legendaryActions: "",
    //     behaviour: "",
    //     lair: "",
    //     imageUrl: "assets/.png",
    //     imageDiscription: ,
},

IvyElemental  : {
    //     name: "",
    //     Pname: "",
    //     size: "",
    //     alignment: "",
    //     armorClass: "",
    //     hitPoints: num,
    //     hitDie: "",
    //     speed: "",
    //     str: num,
    //     dex: num,
    //     con: num,
    //     int: num,
    //     wis: num,
    //     cha: num,
    //     savingThrows "",
    //     skills: "",
    //     damageVulerabilites: "",
    //     damageResistance
    //     damageImmunities: "",
    //     senses: "",
    //     languges: "",
    //     cr: num,
    //     traits: "",
    //     mutate: "",
    //     actions:"",
    //     legendaryActions: "",
    //     behaviour: "",
    //     lair: "",
    //     imageUrl: "assets/.png",
    //     imageDiscription: ,
},

LabyrinthRaptor  : {
    //     name: "",
    //     Pname: "",
    //     size: "",
    //     alignment: "",
    //     armorClass: "",
    //     hitPoints: num,
    //     hitDie: "",
    //     speed: "",
    //     str: num,
    //     dex: num,
    //     con: num,
    //     int: num,
    //     wis: num,
    //     cha: num,
    //     savingThrows "",
    //     skills: "",
    //     damageVulerabilites: "",
    //     damageResistance
    //     damageImmunities: "",
    //     senses: "",
    //     languges: "",
    //     cr: num,
    //     traits: "",
    //     mutate: "",
    //     actions:"",
    //     legendaryActions: "",
    //     behaviour: "",
    //     lair: "",
    //     imageUrl: "assets/.png",
    //     imageDiscription: ,
},

LavaSerpent   : {
    //     name: "",
    //     Pname: "",
    //     size: "",
    //     alignment: "",
    //     armorClass: "",
    //     hitPoints: num,
    //     hitDie: "",
    //     speed: "",
    //     str: num,
    //     dex: num,
    //     con: num,
    //     int: num,
    //     wis: num,
    //     cha: num,
    //     savingThrows "",
    //     skills: "",
    //     damageVulerabilites: "",
    //     damageResistance
    //     damageImmunities: "",
    //     senses: "",
    //     languges: "",
    //     cr: num,
    //     traits: "",
    //     mutate: "",
    //     actions:"",
    //     legendaryActions: "",
    //     behaviour: "",
    //     lair: "",
    //     imageUrl: "assets/.png",
    //     imageDiscription: ,
},

LoreDrakkis   : {
    //     name: "",
    //     Pname: "",
    //     size: "",
    //     alignment: "",
    //     armorClass: "",
    //     hitPoints: num,
    //     hitDie: "",
    //     speed: "",
    //     str: num,
    //     dex: num,
    //     con: num,
    //     int: num,
    //     wis: num,
    //     cha: num,
    //     savingThrows "",
    //     skills: "",
    //     damageVulerabilites: "",
    //     damageResistance
    //     damageImmunities: "",
    //     senses: "",
    //     languges: "",
    //     cr: num,
    //     traits: "",
    //     mutate: "",
    //     actions:"",
    //     legendaryActions: "",
    //     behaviour: "",
    //     lair: "",
    //     imageUrl: "assets/.png",
    //     imageDiscription: ,
},

LuminousBroodmoth   : {
    //     name: "",
    //     Pname: "",
    //     size: "",
    //     alignment: "",
    //     armorClass: "",
    //     hitPoints: num,
    //     hitDie: "",
    //     speed: "",
    //     str: num,
    //     dex: num,
    //     con: num,
    //     int: num,
    //     wis: num,
    //     cha: num,
    //     savingThrows "",
    //     skills: "",
    //     damageVulerabilites: "",
    //     damageResistance
    //     damageImmunities: "",
    //     senses: "",
    //     languges: "",
    //     cr: num,
    //     traits: "",
    //     mutate: "",
    //     actions:"",
    //     legendaryActions: "",
    //     behaviour: "",
    //     lair: "",
    //     imageUrl: "assets/.png",
    //     imageDiscription: ,
},

MajesticAuricorn   : {
    //     name: "",
    //     Pname: "",
    //     size: "",
    //     alignment: "",
    //     armorClass: "",
    //     hitPoints: num,
    //     hitDie: "",
    //     speed: "",
    //     str: num,
    //     dex: num,
    //     con: num,
    //     int: num,
    //     wis: num,
    //     cha: num,
    //     savingThrows "",
    //     skills: "",
    //     damageVulerabilites: "",
    //     damageResistance
    //     damageImmunities: "",
    //     senses: "",
    //     languges: "",
    //     cr: num,
    //     traits: "",
    //     mutate: "",
    //     actions:"",
    //     legendaryActions: "",
    //     behaviour: "",
    //     lair: "",
    //     imageUrl: "assets/.png",
    //     imageDiscription: ,
},

MigratoryGreathorn   : {
    //     name: "",
    //     Pname: "",
    //     size: "",
    //     alignment: "",
    //     armorClass: "",
    //     hitPoints: num,
    //     hitDie: "",
    //     speed: "",
    //     str: num,
    //     dex: num,
    //     con: num,
    //     int: num,
    //     wis: num,
    //     cha: num,
    //     savingThrows "",
    //     skills: "",
    //     damageVulerabilites: "",
    //     damageResistance
    //     damageImmunities: "",
    //     senses: "",
    //     languges: "",
    //     cr: num,
    //     traits: "",
    //     mutate: "",
    //     actions:"",
    //     legendaryActions: "",
    //     behaviour: "",
    //     lair: "",
    //     imageUrl: "assets/.png",
    //     imageDiscription: ,
},

Mindleecher   : {
    //     name: "",
    //     Pname: "",
    //     size: "",
    //     alignment: "",
    //     armorClass: "",
    //     hitPoints: num,
    //     hitDie: "",
    //     speed: "",
    //     str: num,
    //     dex: num,
    //     con: num,
    //     int: num,
    //     wis: num,
    //     cha: num,
    //     savingThrows "",
    //     skills: "",
    //     damageVulerabilites: "",
    //     damageResistance
    //     damageImmunities: "",
    //     senses: "",
    //     languges: "",
    //     cr: num,
    //     traits: "",
    //     mutate: "",
    //     actions:"",
    //     legendaryActions: "",
    //     behaviour: "",
    //     lair: "",
    //     imageUrl: "assets/.png",
    //     imageDiscription: ,
},

MomentumRumbler   : {
    //     name: "",
    //     Pname: "",
    //     size: "",
    //     alignment: "",
    //     armorClass: "",
    //     hitPoints: num,
    //     hitDie: "",
    //     speed: "",
    //     str: num,
    //     dex: num,
    //     con: num,
    //     int: num,
    //     wis: num,
    //     cha: num,
    //     savingThrows "",
    //     skills: "",
    //     damageVulerabilites: "",
    //     damageResistance
    //     damageImmunities: "",
    //     senses: "",
    //     languges: "",
    //     cr: num,
    //     traits: "",
    //     mutate: "",
    //     actions:"",
    //     legendaryActions: "",
    //     behaviour: "",
    //     lair: "",
    //     imageUrl: "assets/.png",
    //     imageDiscription: ,
},

MysteriousEgg   : {
    //     name: "",
    //     Pname: "",
    //     size: "",
    //     alignment: "",
    //     armorClass: "",
    //     hitPoints: num,
    //     hitDie: "",
    //     speed: "",
    //     str: num,
    //     dex: num,
    //     con: num,
    //     int: num,
    //     wis: num,
    //     cha: num,
    //     savingThrows "",
    //     skills: "",
    //     damageVulerabilites: "",
    //     damageResistance
    //     damageImmunities: "",
    //     senses: "",
    //     languges: "",
    //     cr: num,
    //     traits: "",
    //     mutate: "",
    //     actions:"",
    //     legendaryActions: "",
    //     behaviour: "",
    //     lair: "",
    //     imageUrl: "assets/.png",
    //     imageDiscription: ,
},

NascentMetamorph  : {
    //     name: "",
    //     Pname: "",
    //     size: "",
    //     alignment: "",
    //     armorClass: "",
    //     hitPoints: num,
    //     hitDie: "",
    //     speed: "",
    //     str: num,
    //     dex: num,
    //     con: num,
    //     int: num,
    //     wis: num,
    //     cha: num,
    //     savingThrows "",
    //     skills: "",
    //     damageVulerabilites: "",
    //     damageResistance
    //     damageImmunities: "",
    //     senses: "",
    //     languges: "",
    //     cr: num,
    //     traits: "",
    //     mutate: "",
    //     actions:"",
    //     legendaryActions: "",
    //     behaviour: "",
    //     lair: "",
    //     imageUrl: "assets/.png",
    //     imageDiscription: ,
},

Necropanther  : {
    //     name: "",
    //     Pname: "",
    //     size: "",
    //     alignment: "",
    //     armorClass: "",
    //     hitPoints: num,
    //     hitDie: "",
    //     speed: "",
    //     str: num,
    //     dex: num,
    //     con: num,
    //     int: num,
    //     wis: num,
    //     cha: num,
    //     savingThrows "",
    //     skills: "",
    //     damageVulerabilites: "",
    //     damageResistance
    //     damageImmunities: "",
    //     senses: "",
    //     languges: "",
    //     cr: num,
    //     traits: "",
    //     mutate: "",
    //     actions:"",
    //     legendaryActions: "",
    //     behaviour: "",
    //     lair: "",
    //     imageUrl: "assets/.png",
    //     imageDiscription: ,
},

Parcelbeast  : {
    //     name: "",
    //     Pname: "",
    //     size: "",
    //     alignment: "",
    //     armorClass: "",
    //     hitPoints: num,
    //     hitDie: "",
    //     speed: "",
    //     str: num,
    //     dex: num,
    //     con: num,
    //     int: num,
    //     wis: num,
    //     cha: num,
    //     savingThrows "",
    //     skills: "",
    //     damageVulerabilites: "",
    //     damageResistance
    //     damageImmunities: "",
    //     senses: "",
    //     languges: "",
    //     cr: num,
    //     traits: "",
    //     mutate: "",
    //     actions:"",
    //     legendaryActions: "",
    //     behaviour: "",
    //     lair: "",
    //     imageUrl: "assets/.png",
    //     imageDiscription: ,
},

PatagiaTiger  : {
    //     name: "",
    //     Pname: "",
    //     size: "",
    //     alignment: "",
    //     armorClass: "",
    //     hitPoints: num,
    //     hitDie: "",
    //     speed: "",
    //     str: num,
    //     dex: num,
    //     con: num,
    //     int: num,
    //     wis: num,
    //     cha: num,
    //     savingThrows "",
    //     skills: "",
    //     damageVulerabilites: "",
    //     damageResistance
    //     damageImmunities: "",
    //     senses: "",
    //     languges: "",
    //     cr: num,
    //     traits: "",
    //     mutate: "",
    //     actions:"",
    //     legendaryActions: "",
    //     behaviour: "",
    //     lair: "",
    //     imageUrl: "assets/.png",
    //     imageDiscription: ,
},

PhaseDolphin   : {
    //     name: "",
    //     Pname: "",
    //     size: "",
    //     alignment: "",
    //     armorClass: "",
    //     hitPoints: num,
    //     hitDie: "",
    //     speed: "",
    //     str: num,
    //     dex: num,
    //     con: num,
    //     int: num,
    //     wis: num,
    //     cha: num,
    //     savingThrows "",
    //     skills: "",
    //     damageVulerabilites: "",
    //     damageResistance
    //     damageImmunities: "",
    //     senses: "",
    //     languges: "",
    //     cr: num,
    //     traits: "",
    //     mutate: "",
    //     actions:"",
    //     legendaryActions: "",
    //     behaviour: "",
    //     lair: "",
    //     imageUrl: "assets/.png",
    //     imageDiscription: ,
},

PollywogSymbiote   : {
    //     name: "",
    //     Pname: "",
    //     size: "",
    //     alignment: "",
    //     armorClass: "",
    //     hitPoints: num,
    //     hitDie: "",
    //     speed: "",
    //     str: num,
    //     dex: num,
    //     con: num,
    //     int: num,
    //     wis: num,
    //     cha: num,
    //     savingThrows "",
    //     skills: "",
    //     damageVulerabilites: "",
    //     damageResistance
    //     damageImmunities: "",
    //     senses: "",
    //     languges: "",
    //     cr: num,
    //     traits: "",
    //     mutate: "",
    //     actions:"",
    //     legendaryActions: "",
    //     behaviour: "",
    //     lair: "",
    //     imageUrl: "assets/.png",
    //     imageDiscription: ,
},

Porcuparrot   : {
    //     name: "",
    //     Pname: "",
    //     size: "",
    //     alignment: "",
    //     armorClass: "",
    //     hitPoints: num,
    //     hitDie: "",
    //     speed: "",
    //     str: num,
    //     dex: num,
    //     con: num,
    //     int: num,
    //     wis: num,
    //     cha: num,
    //     savingThrows "",
    //     skills: "",
    //     damageVulerabilites: "",
    //     damageResistance
    //     damageImmunities: "",
    //     senses: "",
    //     languges: "",
    //     cr: num,
    //     traits: "",
    //     mutate: "",
    //     actions:"",
    //     legendaryActions: "",
    //     behaviour: "",
    //     lair: "",
    //     imageUrl: "assets/.png",
    //     imageDiscription: ,
},

PouncingShoreshark   : {
    //     name: "",
    //     Pname: "",
    //     size: "",
    //     alignment: "",
    //     armorClass: "",
    //     hitPoints: num,
    //     hitDie: "",
    //     speed: "",
    //     str: num,
    //     dex: num,
    //     con: num,
    //     int: num,
    //     wis: num,
    //     cha: num,
    //     savingThrows "",
    //     skills: "",
    //     damageVulerabilites: "",
    //     damageResistance
    //     damageImmunities: "",
    //     senses: "",
    //     languges: "",
    //     cr: num,
    //     traits: "",
    //     mutate: "",
    //     actions:"",
    //     legendaryActions: "",
    //     behaviour: "",
    //     lair: "",
    //     imageUrl: "assets/.png",
    //     imageDiscription: ,
},

PricklyMarmoset   : {
    //     name: "",
    //     Pname: "",
    //     size: "",
    //     alignment: "",
    //     armorClass: "",
    //     hitPoints: num,
    //     hitDie: "",
    //     speed: "",
    //     str: num,
    //     dex: num,
    //     con: num,
    //     int: num,
    //     wis: num,
    //     cha: num,
    //     savingThrows "",
    //     skills: "",
    //     damageVulerabilites: "",
    //     damageResistance
    //     damageImmunities: "",
    //     senses: "",
    //     languges: "",
    //     cr: num,
    //     traits: "",
    //     mutate: "",
    //     actions:"",
    //     legendaryActions: "",
    //     behaviour: "",
    //     lair: "",
    //     imageUrl: "assets/.png",
    //     imageDiscription: ,
},

Pyroceratops   : {
    //     name: "",
    //     Pname: "",
    //     size: "",
    //     alignment: "",
    //     armorClass: "",
    //     hitPoints: num,
    //     hitDie: "",
    //     speed: "",
    //     str: num,
    //     dex: num,
    //     con: num,
    //     int: num,
    //     wis: num,
    //     cha: num,
    //     savingThrows "",
    //     skills: "",
    //     damageVulerabilites: "",
    //     damageResistance
    //     damageImmunities: "",
    //     senses: "",
    //     languges: "",
    //     cr: num,
    //     traits: "",
    //     mutate: "",
    //     actions:"",
    //     legendaryActions: "",
    //     behaviour: "",
    //     lair: "",
    //     imageUrl: "assets/.png",
    //     imageDiscription: ,
},

QuartzwoodCrasher   : {
    //     name: "",
    //     Pname: "",
    //     size: "",
    //     alignment: "",
    //     armorClass: "",
    //     hitPoints: num,
    //     hitDie: "",
    //     speed: "",
    //     str: num,
    //     dex: num,
    //     con: num,
    //     int: num,
    //     wis: num,
    //     cha: num,
    //     savingThrows "",
    //     skills: "",
    //     damageVulerabilites: "",
    //     damageResistance
    //     damageImmunities: "",
    //     senses: "",
    //     languges: "",
    //     cr: num,
    //     traits: "",
    //     mutate: "",
    //     actions:"",
    //     legendaryActions: "",
    //     behaviour: "",
    //     lair: "",
    //     imageUrl: "assets/.png",
    //     imageDiscription: ,
},

RegalLeosaur  : {
    //     name: "",
    //     Pname: "",
    //     size: "",
    //     alignment: "",
    //     armorClass: "",
    //     hitPoints: num,
    //     hitDie: "",
    //     speed: "",
    //     str: num,
    //     dex: num,
    //     con: num,
    //     int: num,
    //     wis: num,
    //     cha: num,
    //     savingThrows "",
    //     skills: "",
    //     damageVulerabilites: "",
    //     damageResistance
    //     damageImmunities: "",
    //     senses: "",
    //     languges: "",
    //     cr: num,
    //     traits: "",
    //     mutate: "",
    //     actions:"",
    //     legendaryActions: "",
    //     behaviour: "",
    //     lair: "",
    //     imageUrl: "assets/.png",
    //     imageDiscription: ,
},

SanctuarySmasher  : {
    //     name: "",
    //     Pname: "",
    //     size: "",
    //     alignment: "",
    //     armorClass: "",
    //     hitPoints: num,
    //     hitDie: "",
    //     speed: "",
    //     str: num,
    //     dex: num,
    //     con: num,
    //     int: num,
    //     wis: num,
    //     cha: num,
    //     savingThrows "",
    //     skills: "",
    //     damageVulerabilites: "",
    //     damageResistance
    //     damageImmunities: "",
    //     senses: "",
    //     languges: "",
    //     cr: num,
    //     traits: "",
    //     mutate: "",
    //     actions:"",
    //     legendaryActions: "",
    //     behaviour: "",
    //     lair: "",
    //     imageUrl: "assets/.png",
    //     imageDiscription: ,
},

SavaiThundermane  : {
    //     name: "",
    //     Pname: "",
    //     size: "",
    //     alignment: "",
    //     armorClass: "",
    //     hitPoints: num,
    //     hitDie: "",
    //     speed: "",
    //     str: num,
    //     dex: num,
    //     con: num,
    //     int: num,
    //     wis: num,
    //     cha: num,
    //     savingThrows "",
    //     skills: "",
    //     damageVulerabilites: "",
    //     damageResistance
    //     damageImmunities: "",
    //     senses: "",
    //     languges: "",
    //     cr: num,
    //     traits: "",
    //     mutate: "",
    //     actions:"",
    //     legendaryActions: "",
    //     behaviour: "",
    //     lair: "",
    //     imageUrl: "assets/.png",
    //     imageDiscription: ,
},

SawtuskDemolisher  : {
    //     name: "",
    //     Pname: "",
    //     size: "",
    //     alignment: "",
    //     armorClass: "",
    //     hitPoints: num,
    //     hitDie: "",
    //     speed: "",
    //     str: num,
    //     dex: num,
    //     con: num,
    //     int: num,
    //     wis: num,
    //     cha: num,
    //     savingThrows "",
    //     skills: "",
    //     damageVulerabilites: "",
    //     damageResistance
    //     damageImmunities: "",
    //     senses: "",
    //     languges: "",
    //     cr: num,
    //     traits: "",
    //     mutate: "",
    //     actions:"",
    //     legendaryActions: "",
    //     behaviour: "",
    //     lair: "",
    //     imageUrl: "assets/.png",
    //     imageDiscription: ,
},

SeaDasherOctopus  : {
    //     name: "",
    //     Pname: "",
    //     size: "",
    //     alignment: "",
    //     armorClass: "",
    //     hitPoints: num,
    //     hitDie: "",
    //     speed: "",
    //     str: num,
    //     dex: num,
    //     con: num,
    //     int: num,
    //     wis: num,
    //     cha: num,
    //     savingThrows "",
    //     skills: "",
    //     damageVulerabilites: "",
    //     damageResistance
    //     damageImmunities: "",
    //     senses: "",
    //     languges: "",
    //     cr: num,
    //     traits: "",
    //     mutate: "",
    //     actions:"",
    //     legendaryActions: "",
    //     behaviour: "",
    //     lair: "",
    //     imageUrl: "assets/.png",
    //     imageDiscription: ,
},

SerratedScorpion  : {
    //     name: "",
    //     Pname: "",
    //     size: "",
    //     alignment: "",
    //     armorClass: "",
    //     hitPoints: num,
    //     hitDie: "",
    //     speed: "",
    //     str: num,
    //     dex: num,
    //     con: num,
    //     int: num,
    //     wis: num,
    //     cha: num,
    //     savingThrows "",
    //     skills: "",
    //     damageVulerabilites: "",
    //     damageResistance
    //     damageImmunities: "",
    //     senses: "",
    //     languges: "",
    //     cr: num,
    //     traits: "",
    //     mutate: "",
    //     actions:"",
    //     legendaryActions: "",
    //     behaviour: "",
    //     lair: "",
    //     imageUrl: "assets/.png",
    //     imageDiscription: ,
},

SkycatSovereign  : {
    //     name: "",
    //     Pname: "",
    //     size: "",
    //     alignment: "",
    //     armorClass: "",
    //     hitPoints: num,
    //     hitDie: "",
    //     speed: "",
    //     str: num,
    //     dex: num,
    //     con: num,
    //     int: num,
    //     wis: num,
    //     cha: num,
    //     savingThrows "",
    //     skills: "",
    //     damageVulerabilites: "",
    //     damageResistance
    //     damageImmunities: "",
    //     senses: "",
    //     languges: "",
    //     cr: num,
    //     traits: "",
    //     mutate: "",
    //     actions:"",
    //     legendaryActions: "",
    //     behaviour: "",
    //     lair: "",
    //     imageUrl: "assets/.png",
    //     imageDiscription: ,
},

Slitherwisp  : {
    //     name: "",
    //     Pname: "",
    //     size: "",
    //     alignment: "",
    //     armorClass: "",
    //     hitPoints: num,
    //     hitDie: "",
    //     speed: "",
    //     str: num,
    //     dex: num,
    //     con: num,
    //     int: num,
    //     wis: num,
    //     cha: num,
    //     savingThrows "",
    //     skills: "",
    //     damageVulerabilites: "",
    //     damageResistance
    //     damageImmunities: "",
    //     senses: "",
    //     languges: "",
    //     cr: num,
    //     traits: "",
    //     mutate: "",
    //     actions:"",
    //     legendaryActions: "",
    //     behaviour: "",
    //     lair: "",
    //     imageUrl: "assets/.png",
    //     imageDiscription: ,
},

SouvenirSnatcher   : {
    //     name: "",
    //     Pname: "",
    //     size: "",
    //     alignment: "",
    //     armorClass: "",
    //     hitPoints: num,
    //     hitDie: "",
    //     speed: "",
    //     str: num,
    //     dex: num,
    //     con: num,
    //     int: num,
    //     wis: num,
    //     cha: num,
    //     savingThrows "",
    //     skills: "",
    //     damageVulerabilites: "",
    //     damageResistance
    //     damageImmunities: "",
    //     senses: "",
    //     languges: "",
    //     cr: num,
    //     traits: "",
    //     mutate: "",
    //     actions:"",
    //     legendaryActions: "",
    //     behaviour: "",
    //     lair: "",
    //     imageUrl: "assets/.png",
    //     imageDiscription: ,
},

SpelleaterWolverine   : {
    //     name: "",
    //     Pname: "",
    //     size: "",
    //     alignment: "",
    //     armorClass: "",
    //     hitPoints: num,
    //     hitDie: "",
    //     speed: "",
    //     str: num,
    //     dex: num,
    //     con: num,
    //     int: num,
    //     wis: num,
    //     cha: num,
    //     savingThrows "",
    //     skills: "",
    //     damageVulerabilites: "",
    //     damageResistance
    //     damageImmunities: "",
    //     senses: "",
    //     languges: "",
    //     cr: num,
    //     traits: "",
    //     mutate: "",
    //     actions:"",
    //     legendaryActions: "",
    //     behaviour: "",
    //     lair: "",
    //     imageUrl: "assets/.png",
    //     imageDiscription: ,
},

SplendorMare    : {
    //     name: "",
    //     Pname: "",
    //     size: "",
    //     alignment: "",
    //     armorClass: "",
    //     hitPoints: num,
    //     hitDie: "",
    //     speed: "",
    //     str: num,
    //     dex: num,
    //     con: num,
    //     int: num,
    //     wis: num,
    //     cha: num,
    //     savingThrows "",
    //     skills: "",
    //     damageVulerabilites: "",
    //     damageResistance
    //     damageImmunities: "",
    //     senses: "",
    //     languges: "",
    //     cr: num,
    //     traits: "",
    //     mutate: "",
    //     actions:"",
    //     legendaryActions: "",
    //     behaviour: "",
    //     lair: "",
    //     imageUrl: "assets/.png",
    //     imageDiscription: ,
},

StormwildCapridor   : {
    //     name: "",
    //     Pname: "",
    //     size: "",
    //     alignment: "",
    //     armorClass: "",
    //     hitPoints: num,
    //     hitDie: "",
    //     speed: "",
    //     str: num,
    //     dex: num,
    //     con: num,
    //     int: num,
    //     wis: num,
    //     cha: num,
    //     savingThrows "",
    //     skills: "",
    //     damageVulerabilites: "",
    //     damageResistance
    //     damageImmunities: "",
    //     senses: "",
    //     languges: "",
    //     cr: num,
    //     traits: "",
    //     mutate: "",
    //     actions:"",
    //     legendaryActions: "",
    //     behaviour: "",
    //     lair: "",
    //     imageUrl: "assets/.png",
    //     imageDiscription: ,
},

TitanothRex   : {
    //     name: "",
    //     Pname: "",
    //     size: "",
    //     alignment: "",
    //     armorClass: "",
    //     hitPoints: num,
    //     hitDie: "",
    //     speed: "",
    //     str: num,
    //     dex: num,
    //     con: num,
    //     int: num,
    //     wis: num,
    //     cha: num,
    //     savingThrows "",
    //     skills: "",
    //     damageVulerabilites: "",
    //     damageResistance
    //     damageImmunities: "",
    //     senses: "",
    //     languges: "",
    //     cr: num,
    //     traits: "",
    //     mutate: "",
    //     actions:"",
    //     legendaryActions: "",
    //     behaviour: "",
    //     lair: "",
    //     imageUrl: "assets/.png",
    //     imageDiscription: ,
},

TrumpetingGnarr   : {
    //     name: "",
    //     Pname: "",
    //     size: "",
    //     alignment: "",
    //     armorClass: "",
    //     hitPoints: num,
    //     hitDie: "",
    //     speed: "",
    //     str: num,
    //     dex: num,
    //     con: num,
    //     int: num,
    //     wis: num,
    //     cha: num,
    //     savingThrows "",
    //     skills: "",
    //     damageVulerabilites: "",
    //     damageResistance
    //     damageImmunities: "",
    //     senses: "",
    //     languges: "",
    //     cr: num,
    //     traits: "",
    //     mutate: "",
    //     actions:"",
    //     legendaryActions: "",
    //     behaviour: "",
    //     lair: "",
    //     imageUrl: "assets/.png",
    //     imageDiscription: ,
},

VoidBeckoner  : {
    //     name: "",
    //     Pname: "",
    //     size: "",
    //     alignment: "",
    //     armorClass: "",
    //     hitPoints: num,
    //     hitDie: "",
    //     speed: "",
    //     str: num,
    //     dex: num,
    //     con: num,
    //     int: num,
    //     wis: num,
    //     cha: num,
    //     savingThrows "",
    //     skills: "",
    //     damageVulerabilites: "",
    //     damageResistance
    //     damageImmunities: "",
    //     senses: "",
    //     languges: "",
    //     cr: num,
    //     traits: "",
    //     mutate: "",
    //     actions:"",
    //     legendaryActions: "",
    //     behaviour: "",
    //     lair: "",
    //     imageUrl: "assets/.png",
    //     imageDiscription: ,
},

Vulpikeet  : {
    //     name: "",
    //     Pname: "",
    //     size: "",
    //     alignment: "",
    //     armorClass: "",
    //     hitPoints: num,
    //     hitDie: "",
    //     speed: "",
    //     str: num,
    //     dex: num,
    //     con: num,
    //     int: num,
    //     wis: num,
    //     cha: num,
    //     savingThrows "",
    //     skills: "",
    //     damageVulerabilites: "",
    //     damageResistance
    //     damageImmunities: "",
    //     senses: "",
    //     languges: "",
    //     cr: num,
    //     traits: "",
    //     mutate: "",
    //     actions:"",
    //     legendaryActions: "",
    //     behaviour: "",
    //     lair: "",
    //     imageUrl: "assets/.png",
    //     imageDiscription: ,
},

WingfoldPteron  : {
    //     name: "",
    //     Pname: "",
    //     size: "",
    //     alignment: "",
    //     armorClass: "",
    //     hitPoints: num,
    //     hitDie: "",
    //     speed: "",
    //     str: num,
    //     dex: num,
    //     con: num,
    //     int: num,
    //     wis: num,
    //     cha: num,
    //     savingThrows "",
    //     skills: "",
    //     damageVulerabilites: "",
    //     damageResistance
    //     damageImmunities: "",
    //     senses: "",
    //     languges: "",
    //     cr: num,
    //     traits: "",
    //     mutate: "",
    //     actions:"",
    //     legendaryActions: "",
    //     behaviour: "",
    //     lair: "",
    //     imageUrl: "assets/.png",
    //     imageDiscription: ,
},

ZagothMamba  : {
    //     name: "",
    //     Pname: "",
    //     size: "",
    //     alignment: "",
    //     armorClass: "",
    //     hitPoints: num,
    //     hitDie: "",
    //     speed: "",
    //     str: num,
    //     dex: num,
    //     con: num,
    //     int: num,
    //     wis: num,
    //     cha: num,
    //     savingThrows "",
    //     skills: "",
    //     damageVulerabilites: "",
    //     damageResistance
    //     damageImmunities: "",
    //     senses: "",
    //     languges: "",
    //     cr: num,
    //     traits: "",
    //     mutate: "",
    //     actions:"",
    //     legendaryActions: "",
    //     behaviour: "",
    //     lair: "",
    //     imageUrl: "assets/.png",
    //     imageDiscription: ,
},


}

app.innit = () => {
    
    app.monsterCount();
    app.populate();
    app.depopulate();
    app.crSelection();
    // app.monsterDisplayAll();
};

app.populate = () => {
    $("#populateButton").on('click', function(){
        console.log("Click!")
        app.monsterDisplayAll();
    })
}

app.depopulate = () => {
    $("#depopulateButton").on('click', function(){
        console.log("Declick!")
        $(".monsters").empty();
    })
}

app.monsterCount = () => {
    var count = 0;
    var countWIP = 0;
    var FinCount = 0;
    Object.keys(monsterManual).forEach(function (item){
    
        count = count + 1
        if (monsterManual[item].name !="" && monsterManual[item].name != undefined && (monsterManual[item].behaviour == undefined ||monsterManual[item].behaviour == "")){
            countWIP= countWIP + 1;
            console.log("In progress: " + monsterManual[item].name)

        }
            if(monsterManual[item].behaviour !=undefined && monsterManual[item].behaviour != ""){
            FinCount =FinCount+1;
        }
    })
    
    const html1= `<p>Total count: ${count}</p>`;
    const htmlwip=`<p>In progess count: ${countWIP}</p>`;
    const htmlfin=`<p>Compeleted count: ${FinCount}</p>`;
    $(".counter").append(html1 + htmlwip + htmlfin);
}

app.monsterDisplayAll = () => {
    for (item in monsterManual){

        if(monsterManual[item].name != undefined){

        

            const html2 = `<div class="monsterContainer">
            <img src='../${monsterManual[item].imageUrl}' alt= "${monsterManual[item].imageDiscription}">
            
            <h2>${monsterManual[item].name}</h2>
            <p>${monsterManual[item].size} ${monsterManual[item].type}` 
            
            if(monsterManual[item].subtype != "")
            {
                html20=  ` (${monsterManual[item].subtype})`
            }
            else{
                html20 ="";
            }

            const html21=`
            , ${monsterManual[item].alignment}</p>
            <p> Armour Class: ${monsterManual[item].armorClass}</p>
            <p> Hit Points: ${monsterManual[item].hitPoints} (${monsterManual[item].hitdie})</p>
            <p> Speed: ${monsterManual[item].speed}</p>
            <p>Str: ${monsterManual[item].str} Dex: ${monsterManual[item].dex} Con: ${monsterManual[item].con}
            Int: ${monsterManual[item].int} Wis: ${monsterManual[item].wis} Cha: ${monsterManual[item].cha}</p>
            `
            if(monsterManual[item].savingThrows != "")
                {
                    html3=  `<p> Saving Throws: ${monsterManual[item].savingThrows}</p>`
                }
                else{
                    html3 ="";
                }
            
            if(monsterManual[item].skills != "")
                {
                    html4=  `<p>Skills: ${monsterManual[item].skills}</p>`
                } 
                else{
                    html4 ="";
                }

            if(monsterManual[item].damageVulerabilites != "")
                {
                    html5=  `<p>Damage Vulerabilites: ${monsterManual[item].damageVulerabilites}</p>`
                }
                else{
                    html5 ="";
                }
        
            if(monsterManual[item].damageResistance != "")
                {
                    html6=  `<p>Damage Resistances: ${monsterManual[item].damageResistance}</p>`
                }
                else{
                    html6 ="";
                }
        
            if(monsterManual[item].damageImmunities != "")
                {
                    html7=  `<p>Damage Immunities: ${monsterManual[item].damageImmunities}</p>`
                }
                else{
                    html7 ="";
                }

            if(monsterManual[item].conditionImmunities != "")
                {
                    html22=  `<p>Condition Immunities: ${monsterManual[item].conditionImmunities}</p>`
                }
                else{
                    html22 ="";
                }
            
            const html8=`
            <p> Senses: ${monsterManual[item].senses}</p>
            <p> Languges: ${monsterManual[item].languges}</p>
            <p> Locations: ${monsterManual[item].location} &nbsp;&nbsp;&nbsp;&nbsp; Triome: ${monsterManual[item].triome} </p>
            <p> Challenge ${monsterManual[item].cr} ${monsterManual[item].xp}<p><br>
            <p> ${monsterManual[item].traits}</p><br>
            `
        
            if(monsterManual[item].mutate != "")
            {
                html9=  `<p> Upon Mutation: ${monsterManual[item].mutate}</p>`
            }
            else{
                html9 ="";
            }

            const html10=`
            <h3>Actions</h3>
            <p> ${monsterManual[item].actions}</p><br>
            `
            
            if(monsterManual[item].legendaryActions != "")
            {
                html11=  `
                <h3>Legendary Actions</h3>
                <p>${monsterManual[item].legendaryActions}</p>
                `
            }
            else{
                html11 ="";
            }

            const html12=`
            <p>${monsterManual[item].behaviour}</p>
            `
            
            if(monsterManual[item].lair != "")
            {
                html13=  `
                <h3>Lair Actions</h3>
                <p>${monsterManual[item].lair}</p>
                `
            }
            else{
                html13 ="";
            }


            $(".monsters").append(html2 + html20 + html21 + html3 + html4 + html5 + html6 + html7 + html22 + html8 + html9 + html10 + html11 + html12 + html13);

        }
    }
}

app.crSelection = () => {
    $("#selectCR").on('click', function(){
        var min = $('#minCR').val();
        var max = $('#maxCR').val();
        console.log("crSelection Click test!");
        console.log("Min Cr is : ", min);
        console.log("Max Cr is : ", max);
        for (item in monsterManual){

            if(monsterManual[item].cr >= min && monsterManual[item].cr <= max){
    
            
    
                const html2 = `<div class="monsterContainer">
                <img src='../${monsterManual[item].imageUrl}' alt= "${monsterManual[item].imageDiscription}">
                
                <h2>${monsterManual[item].name}</h2>
                <p>${monsterManual[item].size} ${monsterManual[item].type}` 
                
                if(monsterManual[item].subtype != "")
                {
                    html20=  ` (${monsterManual[item].subtype})`
                }
                else{
                    html20 ="";
                }
    
                const html21=`
                , ${monsterManual[item].alignment}</p>
                <p> Armour Class: ${monsterManual[item].armorClass}</p>
                <p> Hit Points: ${monsterManual[item].hitPoints} (${monsterManual[item].hitdie})</p>
                <p> Speed: ${monsterManual[item].speed}</p>
                <p>Str: ${monsterManual[item].str} Dex: ${monsterManual[item].dex} Con: ${monsterManual[item].con}
                Int: ${monsterManual[item].int} Wis: ${monsterManual[item].wis} Cha: ${monsterManual[item].cha}</p>
                `
                if(monsterManual[item].savingThrows != "")
                    {
                        html3=  `<p> Saving Throws: ${monsterManual[item].savingThrows}</p>`
                    }
                    else{
                        html3 ="";
                    }
                
                if(monsterManual[item].skills != "")
                    {
                        html4=  `<p>Skills: ${monsterManual[item].skills}</p>`
                    } 
                    else{
                        html4 ="";
                    }
    
                if(monsterManual[item].damageVulerabilites != "")
                    {
                        html5=  `<p>Damage Vulerabilites: ${monsterManual[item].damageVulerabilites}</p>`
                    }
                    else{
                        html5 ="";
                    }
            
                if(monsterManual[item].damageResistance != "")
                    {
                        html6=  `<p>Damage Resistances: ${monsterManual[item].damageResistance}</p>`
                    }
                    else{
                        html6 ="";
                    }
            
                if(monsterManual[item].damageImmunities != "")
                    {
                        html7=  `<p>Damage Immunities: ${monsterManual[item].damageImmunities}</p>`
                    }
                    else{
                        html7 ="";
                    }
    
                if(monsterManual[item].conditionImmunities != "")
                    {
                        html22=  `<p>Condition Immunities: ${monsterManual[item].conditionImmunities}</p>`
                    }
                    else{
                        html22 ="";
                    }
                
                const html8=`
                <p> Senses: ${monsterManual[item].senses}</p>
                <p> Languges: ${monsterManual[item].languges}</p>
                <p> Locations: ${monsterManual[item].location} &nbsp;&nbsp;&nbsp;&nbsp; Triome: ${monsterManual[item].triome} </p>
                <p> Challenge ${monsterManual[item].cr} ${monsterManual[item].xp}<p><br>
                <p> ${monsterManual[item].traits}</p><br>
                `
            
                if(monsterManual[item].mutate != "")
                {
                    html9=  `<p> Upon Mutation: ${monsterManual[item].mutate}</p>`
                }
                else{
                    html9 ="";
                }
    
                const html10=`
                <h3>Actions</h3>
                <p> ${monsterManual[item].actions}</p><br>
                `
                
                if(monsterManual[item].legendaryActions != "")
                {
                    html11=  `
                    <h3>Legendary Actions</h3>
                    <p>${monsterManual[item].legendaryActions}</p>
                    `
                }
                else{
                    html11 ="";
                }
    
                const html12=`
                <p>${monsterManual[item].behaviour}</p>
                `
                
                if(monsterManual[item].lair != "")
                {
                    html13=  `
                    <h3>Lair Actions</h3>
                    <p>${monsterManual[item].lair}</p>
                    `
                }
                else{
                    html13 ="";
                }
    
    
                $(".monsters").append(html2 + html20 + html21 + html3 + html4 + html5 + html6 + html7 + html22 + html8 + html9 + html10 + html11 + html12 + html13);
    
            }
        }
    })
}

$(function(){
    app.innit();
    
})